### PR TITLE
Working Draft of Cute Kitties

### PR DESCRIPTION
**Pull request by DAppProletariat**
Adding my working draft of the "Cute Kitties and Where to Find Them" article

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
@DAppProletariat Is this in progress, or complete?

**Comment by DAppProletariat** [comment]
@ChrisChinchilla It's in progress. The ideas are there, I just have to work on the narrative, add some code, and so forth. Shared it to see if you have any thoughts on the article before I wrap it up.

**Comment by ChrisChinchilla** [comment]
@DAppProletariat OK great, just as long as we stick as much as possible to the practical angle :)

**Comment by DAppProletariat** [comment]
@ChrisChinchilla By practical angle, do you mean implementation tutorials? Because I've been working on this from a more "technically focused" conceptual perspective.

**Pull request merged**
