### PR TITLE
Deploy fullstack dApp to AWS

### LINKED ISSUE #51: Deploying Full stack Dapp to AWS
We have an existing tutorial collection that takes new web3 developers from beginning steps to a functioning full stack web3 dapp.

https://kauri.io/collection/5b8e401ee727370001c942e3

We want to add a new tutorial to this collection to show the steps to deploy application side of the dapp to AWS. In this particular case, also show the reader how to deploy their smart contract to running on an AWS managed blockchain instance.

Ideally the deployment process is maintainable as code changes, the app should also update.

The article should follow on from earlier parts of the series, use simple technical english and as little passive voice as possible. If you make a PR to this repo it offers advice on your text via a CI process.

### PR DESCRIPTION
**Pull request by mul1sh**
Fixes #51

### CODE REVIEW

**Comment by mul1sh** [comment]
@ChrisChinchilla any feedback on this, thanks 🙂

**Comment by ChrisChinchilla** [comment]
Been out for a few days, on this today @mul1sh

**Comment by mul1sh** [comment]
@ChrisChinchilla no worries, also kindly approve me so that i might be able to submit this issue. Thanks.

**Comment by ChrisChinchilla** [comment]
Awwright @mul1sh edited and reviewed, pretty good, mostly small things. If you're happy we'll merge and can get published.

**Comment by mul1sh** [comment]
@ChrisChinchilla it looks good to me 😃 , so we can definitely merge and get it published. Thanks

**Comment by ChrisChinchilla** [comment]
@mul1sh Great! Next steps, create a Kauri account, publish (with tags and an image) and off we go!

**Comment by mul1sh** [comment]
@ChrisChinchilla [done](https://kauri.io/article/26165036e74b44a69e6aeb2137c71d54/v1/deploying-a-full-stack-dapp-to-amazon-ec2) thanks 😃

**Comment by mul1sh** [comment]
Anything else you need done on this, thanks? @ChrisChinchilla

**Pull request merged**
