### PR TITLE
Draft of ERC721 Cute Kitties

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
Reapplying merged branch from @DAppProletariat

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
@DAppProletariat So in general I was hoping for something a lot more practical. So for example, here's some places I think we could add a bit more practical advice. But there are likely more.

When discussing the ERC process and ERC standards, can you show some code examples? Especially showing the tokens for some of the projects you mention (if available) would be great. Not  just in a gist, but actual code, explained in overview.

I'd love a few more practical examples in the "6. Tying non-fungible tokens and decentralized exchanges together" section. What could this mean on a day-to-day basis for a person using NFTs? Trading their work, exchanging their work etc etc.

I don't really see the section "4. A brief introduction to the ERC process".

I don't really see the "1. A brief introduction on exchanges (crypto and fiat)" or "2. A brief primer on collectibles (physical and digital)" sections.

That's it for now, a bit mroe polish and I think this could be a great post :)

**Comment by DAppProletariat** [comment]
@ChrisChinchilla thanks for the feedback, I'm working on it. I'll submit a PR with an update within a couple of days.

**Comment by ChrisChinchilla** [comment]
This is soooooo much better @DAppProletariat 👏. Let me know if you are happy with my changes, and if so, we'll get this published next week.

**Review by DAppProletariat — APPROVED** [review]
Thanks, @ChrisChinchilla , I appreciate the feedback and edits. 
I'm happy with the content of our draft, I just noticed some minor syntax and language stuff that I'll work on today. If you're happy with that, then I'm ready to publish it next week.

**Comment by ChrisChinchilla** [comment]
Closes #22

**Pull request merged**
