### PR TITLE
first draft Plasma article

### PR DESCRIPTION
**Pull request by cspannos**
Second pull request, in place of the first.

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
Great @cspannos will get to reviewing soon!

**Comment by ChrisChinchilla** [comment]
Sorry to be a pain, but @cspannos can you add as a branch of this repo, or direct branch from your fork? For some reason it's a submodule, which makes it pretty hard to review using the standard GitHub PR interface.

**Comment by cspannos** [comment]
Oh my... Sorry! Not sure what I did there. Will work to fix now.

**Comment by cspannos** [comment]
@ChrisChinchilla I've crated a new 'plasma-roundup' branch which I hope you are able to view now.

**Comment by ChrisChinchilla** [comment]
Really sorry @cspannos but I still can't see anything, I can't see a folder, I can't see the new branch you mean, and even the submodule seems empty. You can also just create a branch on the main repo if you want, that's fine too :)

**Comment by cspannos** [comment]
@ChrisChinchilla No worries... Can you see it here? https://github.com/kauri-io/Content/blob/plasma-roundup/plasma-roundup/draft-plasma-article.md 

If you can't let me know and I will try again. Very sorry to have done something funny so start with....

**Comment by ChrisChinchilla** [comment]
I really don't understand what's up with this PR @cspannos but I can now checkout the file, but still can't add comments to review here, so I just started a new PR #21 :)

**Pull request closed without merging**
