### PR TITLE
PR for gitcoin bounty: `Deploying Full Stack Dapp To Google Cloud`

### PR DESCRIPTION
**Pull request by mrdavey**
Google Cloud has static hosting, however it is quite a complex and convoluted process for a dApp frontend. Therefore I utilised Firebase, which is owned/operated by Google, and an abstraction on top of Google Cloud infrastructure. I also go into more details in the second section to explain why Firebase is superior in this instance.

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
@mrdavey Hmm, OK, but this was the brief, and the previous posts covering Azure and AWS were also complex. It might have been good to check this was an OK alternative first.

How about this for a plan. You fulfil the bounty as planned, and we'll also take the Firebase post, adding a tip on top of the bounty for that?

**Comment by mrdavey** [comment]
OK can do @ChrisChinchilla, although AWS and Azure ones are dealing with a different setup (blockchain workbench and kaleido). This new one would be more similar to the Heroku tutorial, using Infura as shown in the previous Truffle tutorials.

**Comment by ChrisChinchilla** [comment]
That is fine @mrdavey !

**Comment by mrdavey** [comment]
OK done @ChrisChinchilla ! 😅

**Comment by ChrisChinchilla** [comment]
@mrdavey Added some formatting and grammar fixes. If you're happy with them, then create an account on kauri.io and publish away. Please add a header image at least and some tags.

**Comment by mrdavey** [comment]
Sure. Can this PR be approved and merged for the Gitcoin bounty?

**Comment by ChrisChinchilla** [comment]
@mrdavey I will merge, but the bounty is paid out when the article is published to Kauri, sorry, there's no real way to connect that to GitCoin unfortunately…

**Comment by mrdavey** [comment]
@ChrisChinchilla ok done: https://kauri.io/article/2ee06d313ffa41348f916afa13a78bbd/v1/deploying-a-full-stack-dapp-to-google-cloud

**Pull request merged**
