### PR TITLE
Token Curated Registry article

### PR DESCRIPTION
**Pull request by Destiner**
Related to #30.

WIP so making a draft PR.

### CODE REVIEW

**Comment by Destiner** [comment]
@ChrisChinchilla pr is ready for review.

**Comment by ChrisChinchilla** [comment]
Sorry @Destiner I completely forgot to push my changes from weeks ago! Let me know what you think and if you're happy I think we're ready to get this live.

**Comment by ChrisChinchilla** [comment]
I think I also need to test the code works yet, but that's fine.

**Comment by Destiner** [comment]
Sounds good. I've added a short readme to the source code repo with build & test instructions. Feel free to ask questions about the code & repo.

**Review by ChrisChinchilla — APPROVED** [review]

**Comment by ChrisChinchilla** [comment]
OK, looks good. Next step @Destiner please create an account on Kauri, and post when you're ready, then I'll pay the bounty.

**Comment by Destiner** [comment]
Everything looks good on my side. The article [is live at Kauri](https://kauri.io/article/5d256b3a16c3430080718f29d6758366/v1/incentivizing-high-quality-curation-with-a-token-curated-registry).

**Pull request merged**
